config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :users do
    resources :user_games, only: [:index, :create]
    resources :user_platforms, only: [:create]
    member do
      post :add_friend
      post :un_friend
    end
  end

  resources :user_game_user_platforms, only: [:create]

  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  # when user logged in, redirect user to dashboard as user's root
  get "/user" => 'pages#dashboard', :as => :user_root

  resources :chatrooms, only: [:create] do
    resources :messages, only: :create
    resources :chatroom_users, only: :create
  end

  get 'games/:id', to: 'games#show', as: :game

  resources :notifications, only: [:create, :index]


end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  # acts_as_token_authenticatable

  has_many :user_platforms, dependent: :destroy
  has_many :user_games, dependent: :destroy
  has_many :user_game_user_platforms, through: :user_games, dependent: :destroy
  has_many :chatroom_users, dependent: :destroy
  has_many :chatrooms, through: :chatroom_users, dependent: :destroy
  has_many :messages
  has_many :friend_user_relationships, foreign_key: :user_id, class_name: 'Friendship'
  has_many :friend_users, through: :friend_user_relationships, source: :friend_user

  has_many :user_relationship, foreign_key: :friend_user_id, class_name: 'Friendship'
  has_many :users, through: :user_relationships, source: :user

  has_many :notifications

  has_one_attached :photo

  def add_friend(user_id)
    friend_user_relationships.create(friend_user_id: user_id)
  end

  def un_friend(user_id)
    friend_user_relationships.find_by(friend_user_id: user_id).destroy
  end

  def is_friend?(user_id)
    relationship = Friendship.find_by(user_id: id, friend_user_id: user_id)
    return true if relationship
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  include HtmlRender
  before_action :set_user, only: [:add_friend, :un_friend]
  skip_before_action :authenticate_user!
  before_action :skip_authorization
  # skip_before_action :verify_authorized

  def index
    load_users
    respond_to do |format|
      format.html { render }
      format.json {
        render json: {
          users_html: render_html_content(partial: "user", layout: false, locals: { users: @searched_users })
        }
      }
    end
  end

  def add_friend
    if current_user.add_friend(@user.id)
      respond_to do |format|
        format.html { render }
        format.json {
          render json: { success: true }
        }
      end
      # redirect_to user_root_path
    end
  end

  def un_friend
    if current_user.un_friend(@user.id) && @user.un_friend(current_user.id)
      # respond_to do |format|
      #   format.html { redirect_to user_root_path }
      #   format.js
      # end
      redirect_to user_root_path
    end
  end

  private

  def set_user
    @user = User.find(params[:id])
  end

  def load_users
    @searched_users =
    if params[:query]
      @searched_users = User.where("user_name ILIKE ? AND id != ?", "%#{params[:query]}%", current_user.id.to_s)
    else
      User.where.not(id: current_user.id)
    end
  end

end

app/views/users/_user.html.erb
<% users.each do |user| %>
  <li data-user=<%= user.id %> class="d-flex justify-content-between mt-2">
    <% if user.photo.attached? %>
      <span><%= cl_image_tag user.photo.key, alt: "#{user.user_name}", class: "avatar"%> <%= user.user_name %></span>
    <% else %>
      <span><%=  image_tag "avatar_pink.png", class: "avatar" %><%= user.user_name %></span>
    <% end %>
    <% if current_user.is_friend?(user.id) && user.is_friend?(current_user.id) %>
      <%= link_to un_friend_user_path(user.id), method: :post, remote: true do %>
        <i class="fas fa-user-times friendship"></i>
      <% end %>
    <% elsif current_user.is_friend?(user.id) %>
      <i class="fas fa-question-circle"></i>
    <% else %>
      <div data-controller='addfriend'>
        <span data-action='click->addfriend#friendRequest'><i class="fas fa-user-plus friendship"></i></span>
      </div>
    <% end %>
  </li>
<% end %>

app/views/users/friendship.js.erb
// function renderUser(userHTML) {
//   const user = document.querySelector("[data-user='<%= @user.id %>']");
//   user.outerHTML = userHTML;
// }

// renderUser('<%= j render @user %>');