config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :users do
    resources :user_games, only: [:index, :create]
    resources :user_platforms, only: [:create]
    member do
      post :add_friend
      post :un_friend
    end
  end

  resources :user_game_user_platforms, only: [:create]

  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  # when user logged in, redirect user to dashboard as user's root
  get "/user" => 'pages#dashboard', :as => :user_root

  resources :chatrooms, only: [:create] do
    resources :messages, only: :create
    resources :chatroom_users, only: :create
  end

  get 'games/:id', to: 'games#show', as: :game

  resources :notifications, only: [:create, :index]


end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer mt-5">
  <div class="footer-links">
    <a href="#"><i class="fab fa-github"></i></a>
    <a href="#"><i class="fab fa-instagram"></i></a>
    <a href="#"><i class="fab fa-facebook"></i></a>
    <a href="#"><i class="fab fa-twitter"></i></a>
    <a href="#"><i class="fab fa-linkedin"></i></a>
  </div>
  <div class="footer-copyright">
    <p>Coded with <i class="fas fa-heart"></i> by Zuzu</p>
    <p>Big thanks for the great <a href="https://api.rawg.io/docs/">RAWG API</a> of all the game datas🙏!</p>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon fixed-top">
  <%= link_to "/", class: "navbar-brand d-flex" do %>
    <%#= image_tag "gamer-boy-mascot-logo-01-scaled.jpg", class: "logo" %>
    <i class="fas fa-ghost"></i>
    <span>GAMEBOOK</span>
  <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <li class="nav-item active">
          <%= link_to "Home", root_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "My page", user_root_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "My GameBook", user_user_games_path(current_user), class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "#", class: "nav-link" do %>
            <i class="far fa-bell"></i>
          <% end %>
        </li>
        <li class="nav-item dropdown">
          <% if current_user.photo.attached? %>
            <%= cl_image_tag current_user.photo.key, class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <% else %>
            <%= image_tag "avatar_pink.png", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <% end %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "Action", "#", class: "dropdown-item" %>
            <%= link_to "Another action", "#", class: "dropdown-item" %>
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>