config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :users do
    resources :user_games, only: [:index, :create]
    resources :user_platforms, only: [:create]
    member do
      post :add_friend
      post :un_friend
    end
  end

  resources :user_game_user_platforms, only: [:create]

  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  # when user logged in, redirect user to dashboard as user's root
  get "/user" => 'pages#dashboard', :as => :user_root

  resources :chatrooms, only: [:create] do
    resources :messages, only: :create
    resources :chatroom_users, only: :create
  end

  get 'games/:id', to: 'games#show', as: :game

  resources :notifications, only: [:create, :index]


end

app/views/pages/_game_card.html.erb
<% responses.each do |response|  %>
  <div class="card game-card" data-controller="addgame" data-game-id=<%= response["id"] %> >
      <%= image_tag response["background_image"] == nil ? "https://media.istockphoto.com/vectors/coming-soon-neon-banner-vector-template-glowing-night-bright-sign-vector-id1144514162?k=6&m=1144514162&s=612x612&w=0&h=np7sPl0hycuFTiDgfKCZFy3SF7XCjbRTcyF-sSKfMO8=" : response["background_image"],class:"card-img-top", width:320, height: 200, alt: response['name'] %>
    <div class="card-body">
      <h4 class="card-title"><%= link_to response['name'], game_path(response["id"]) %> </h4>
      <div class="game-rate d-flex justify-content-between">
        <span class="card-text"><small><i class="fas fa-star"></i>&nbsp&nbsp<%= response['rating']%></small></span>
        <span class="game-release"><small><i class="far fa-calendar-alt"></i>&nbsp&nbsp<%= response["released"] %></small></span>
      </div>
      <p class="game-genres"><small>
        <%= response['genres'].map { |genre| genre['name'] }.join(" | ") %>
      </small></p>
      <hr>
        <!-- checkboxes of platform so user can click to choose the platform of their blongs game -->
        <div class="game-platforms">
          <% response['platforms'].each do |platform| %>
            <% if current_user %>
              <input type="checkbox" class="checkbox-platform" data-target="addgame.platform" data-platform="<%= platform['platform']["name"] %>" data-game="<%= response['name'] %>" data-user=<%= current_user.id %> id=<%= "#{response['id']}-#{platform["platform"]["id"]}" %>>
              <label for=<%= "#{response['id']}-#{platform["platform"]["id"]}" %>><%=platform['platform']["name"]%></label>
            <% else %>
              <input type="checkbox" class="checkbox-platform" data-target="addgame.platform" id=<%= "#{response['id']}-#{platform["platform"]["id"]}" %>>
              <label for=<%= "#{response['id']}-#{platform["platform"]["id"]}" %>><%=platform['platform']["name"]%></label>
            <% end %>
          <% end %>
        </div>
        <!-- end of checkbox div -->
        <div class="act-wrapper d-flex">
          <!-- wish-button -->
          <div class="add-wish">
            <%= link_to "#", class: "wish-btn" do %>
              <i class="fas fa-gift"></i>
            <% end %>
          </div>
          <!-- end of wish-button -->
          <!-- add to my collection button -->
          <% if current_user %>
            <button class="btn btn-primary add-game" date-remote="true" data-action="click->addgame#saveGame"><i class="fas fa-plus"></i>&nbsp&nbspmy collection</button>
          <% else %>
            <%= link_to new_user_session_path, class: "btn btn-primary add-game" do %>
              <i class="fas fa-plus">&nbsp&nbsp</i> my collection
            <% end %>
          <% end %>
          <%#= link_to "Add to my collection", user_user_consoles_path(current_user), method: :post, class: "btn btn-primary add-game", data: {action: "click->addgame#saveGame"} %>
          <!-- end of the add button -->
        </div>
    </div>
  </div>
<% end %>

app/views/pages/_load_chatroom.html.erb
_load_chatroom.html.erb

app/views/pages/_load_user.html.erb
<div class="container-user">
  <% if user.photo.attached? %>
    <%= cl_image_tag user.photo.key, alt: "#{user.user_name}", class: "avatar-large"%>
  <% else %>
    <%=  image_tag "avatar_pink.png", class: "avatar-large" %>
  <% end %>
  <h6 class=user_name><%= user.user_name %></h6>
  <hr>
  <ul>
    <li class="d-flex justify-content-between">
      <span class="d-flex justify-content-begin">
        <a class="btn btn-square" href="">G</a>
        <p>&nbsp my games</p>
      </span>
      <span><h6><%= user_games.count %></h6></span>
    </li>
    <li class="d-flex justify-content-between mt-2">
      <span class="d-flex justify-content-begin">
        <a class="btn btn-square" href="">P</a>
        <p>&nbsp my platforms</p>
      </span>
      <span><h6> <%= platforms.count %> </h6></span>
    </li>
  </ul>
    <% platforms.each do |platform| %>
      <input type="checkbox" class="checkbox-platform" id=<%= platform.id %>>
      <label for=<%= platform.id %>><%=platform.platform_name%> <%=platform.user_games.count%></label>
    <% end %>
</div>

app/views/pages/_my_game_card.html.erb
<% responses.each do |response|  %>
  <div class="card game-card" data-game-id=<%= response["id"]  %> >
      <%= image_tag response["background_image"] == nil ? "https://media.istockphoto.com/vectors/coming-soon-neon-banner-vector-template-glowing-night-bright-sign-vector-id1144514162?k=6&m=1144514162&s=612x612&w=0&h=np7sPl0hycuFTiDgfKCZFy3SF7XCjbRTcyF-sSKfMO8=" : response["background_image"],class:"card-img-top", width:320, height: 200, alt: response['name'] %>
    <div class="card-body">
      <h4 class="card-title"><%= link_to response['name'], game_path(response["id"]) %> </h4>
      <div class="game-rate d-flex justify-content-between">
        <span class="card-text"><small><i class="fas fa-star"></i>&nbsp&nbsp<%= response['rating']%></small></span>
        <span class="game-release"><small><i class="far fa-calendar-alt"></i>&nbsp&nbsp<%= response["released"] %></small></span>
      </div>
      <p class="game-genres"><small>
        <%= response['genres'].map { |genre| genre['name'] }.join(" | ") %>
      </small></p>
      <hr>
        <!-- checkboxes of platform so user can click to choose the platform of their blongs game -->
        <div class="game-platforms">
          <% response['platforms'].each do |platform| %>
            <% if current_user %>
              <input type="checkbox" class="checkbox-platform" data-target="addgame.platform" data-platform="<%= platform['platform']["name"] %>" data-game="<%= response['name'] %>" data-user=<%= current_user.id %> id=<%= "#{response['id']}-#{platform["platform"]["id"]}" %>>
              <label for=<%= "#{response['id']}-#{platform["platform"]["id"]}" %>><%=platform['platform']["name"]%></label>
            <% else %>
              <input type="checkbox" class="checkbox-platform" data-target="addgame.platform" id=<%= "#{response['id']}-#{platform["platform"]["id"]}" %>>
              <label for=<%= "#{response['id']}-#{platform["platform"]["id"]}" %>><%=platform['platform']["name"]%></label>
            <% end %>
          <% end %>
        </div>
        <!-- end of checkbox div -->
        <div class="act-wrapper d-flex">
          <!-- delete-button -->
          <div class="delete-game mx-3">
            <%= link_to "#", class: "delete-btn" do %>
              <i class="fas fa-trash"></i>
            <% end %>
          </div>
          <!-- end of delete-button -->
          <!-- status drop-down-->
            <i class="fas fa-battery-half"></i>
          <%#= link_to "Add to my collection", user_user_consoles_path(current_user), method: :post, class: "btn btn-primary add-game", data: {action: "click->addgame#saveGame"} %>
          <!-- end of the status -->
        </div>
    </div>
  </div>
<% end %>

app/views/pages/_search_bar.html.erb
  <!-- this is the form to send params to the back to launch the search in RAWG Api -->
  <div class="search-wrap">
    <%= form_tag "",
      class: "d-flex justify-content-around mx-1",
      data: {action: "submit->search#showCards"},
      # remote: true,
      method: "get" do
    %>
      <%= text_field_tag :game,
        params[:game],
        class: "form-control ml-auto mr-2",
        data: {target: "search.game"},
        placeholder: "#{games_count} games to search!"
      %>
      <%= select_tag :platform,
        options_for_select(platforms),
        data: {target: "search.platform"},
        class: "form-control ml-auto mr-2"
      %>

      <%= select_tag :genre,
        options_for_select(genres),
        data: {target: "search.genre"},
        class: "form-control ml-auto mr-2"
      %>

      <button type="submit" class="btn btn-primary btn-search">
        <i class="fas fa-search"></i>
      </button>
    <% end %>
  </div>
  <!-- end of the search action, then to render the result in the following game cards section -->

app/views/pages/_search_user.html.erb
  <!-- this is the form to search users to add to the friend list -->
  <div class="search-wrap">

    <%= form_tag "",
      class: "d-flex justify-content-around  mx-1",
      data: { action: "submit->users#searchUser" },
      # remote: true,
      method: "get" do
    %>
      <%= text_field_tag :query,
        params[:query],
        class: "form-control ml-auto mr-2 user-form",
        data: {target: "users.name"},
        placeholder: "Find user"
      %>

      <button type="submit" class="btn btn-primary btn-search">
        <i class="fas fa-search"></i>
      </button>

      <%#= submit_tag "<i class="fas fa-search"></i>", class: "btn btn-primary mr-auto"%>
    <% end %>

  </div>
  <!-- end of the search action, then to render the result in the following game cards section -->

app/views/pages/dashboard.html.erb
<div class="dash-container">
  <div class="row">
  <div class="content-grid">
    <!-- user profile section, 1fr -->
    <div class="user-profile">
      <%= render 'load_user', user: current_user, platforms: @user_platforms, user_games: @user_games %>
    </div>
    <!-- end of user profile section -->

    <!-- main game section, 2fr -->
    <div class="games-section">
      <div class="game-section-container">

        <!-- search bar -->
        <div class="search-bar" data-controller="search">
          <%= render 'search_bar', platforms: @platforms, genres: @genres, games_count: @games_count %>

          <!-- show the search result with game cards -->
          <div class="container my-3">
            <div class="card-grid-sm" data-target="search.results">
            </div>
          </div>
          <!-- game cards end -->
        </div>
        <!-- search bar and card render end -->

        <h3>My Games</h3>
        <div class="card-grid-sm">
          <% if !@user_games.empty? && @user_games[0]['error'] != "The monthly API limit reached" %>
            <%= render "my_game_card", responses: @user_games %>
          <% end %>
        </div>
      </div>

    </div>
    <!-- end of main game section-->

     <!-- user action and notification sesction, 1fr -->
    <div class="user-action">
      <div class="container">
        <!-- this is the part user can search other user to add to friend -->
        <div class="search-user" data-controller="users">
          <%= render 'search_user' %>
          <div id="user-list">
            <ul data-target="users.userList">

            </ul>
          </div>
        </div>

        <hr>
        <!-- this is the part of user's friends list -->
        <div class="friends" data-controller="chatroom">
          <h6>My Friends</h6>
          <ul>
            <% @friends.each do |friend| %>
              <li class="d-flex justify-content-between mt-2" data-friend=<%= friend.id %>  data-target="chatroom.friend">
                <% if friend.photo.attached? %>
                  <span><%= cl_image_tag friend.photo.key, alt: "#{friend.user_name}", class: "avatar"%> <%= friend.user_name %></span>
                <% else %>
                  <span><%= image_tag "avatar_pink.png", alt: "#{friend.user_name}", class: "avatar"%> <%= friend.user_name %></span>
                <% end %>
                <span><i class="fas fa-comments chat-btn" data-action="click->chatroom#initChatroom" data-friend=<%= friend.id %>></i></span>
              </li>
            <% end %>
          </ul>
          <!-- render the chatroom partial -->
          <div class="chatbox" data-target="chatroom.chatContainer">

          </div>
          <!-- end of chatroom partial -->
        </div>
        <!-- end of friends list -->
      </div>
    </div>
    <!-- end of user action section -->


  </div>
  </div>
</div>

app/views/pages/home.html.erb
<div class="banner">
<h1>Time to open your GameBook and play with your friends!</h1>
<%= link_to "Join now!", new_user_session_path, class: "home-login" %>
</div>

<div class="games-container mt-5">
  <div class="games-set">
    <%# if current_user %>
      <!-- search bar -->
      <div class="search-bar" data-controller="search">
        <%= render 'search_bar', platforms: @platforms, genres: @genres, games_count: @games_count %>

        <!-- show the search result with game cards -->
        <div class="container my-3" data-controller="addgame">
          <div class="card-grid-lg" data-target="search.results">
          </div>
        </div>
        <!-- game cards end -->
      </div>
      <!-- search bar and card render end -->
    <%# end %>


    <h2 class="my-5">Games on the trend</h2>
    <div class="game-cards">
      <div class="card-grid-lg" data-controller="addgame">
      <% if @responses.length != 0 %>
        <%= render 'game_card', responses: @responses %>
      <% else %>
        <h3>This website is under construction, it will come back soon...</h3>
      <% end %>
      </div>
    </div>
  </div>
</div>